# Copyright (c) 2000-2018, Board of Trustees of Leland Stanford Jr. University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

version: '3'

services:
  lockss-webui:
    build:
      context: docker/lockss-webui
    image: lockss/lockss-webui
    ports:
      - "80:80"
    links:
      - lockss-metadata-service
      - lockss-repository-service
#      - lockss-openwayback

  lockss-configuration-service:
    build:
      context: docker/lockss-image
      args:
        SVC_NAME: ${CFG_ART}
        SVC_VERSION: ${CFG_VERSION}
        SVC_PORT: ${CFG_REST_PORT}
    image: lockss/lockss-configuration-service:${CFG_VERSION}
    ports:
      - "${CFG_REST_PORT}:${CFG_REST_PORT}"
      - "${CFG_UI_PORT}:${CFG_UI_PORT}"
      - "${JMS_PORT}:${JMS_PORT}"
    command: "${CFG_CMD}"
    links:
      - lockss-repository-service
    volumes:
      - ./config/plugins:/opt/lockss/BOOT-INF/lib
      - ./config/tdbxml:/opt/lockss/config/tdbxml
      - ./config/cluster:/opt/lockss/config/cluster
      - ./config/host:/opt/lockss/config/host
      - ./config/lockss-configuration-service:/opt/lockss/config/lockss-configuration-service
      - ./storage/lockss-configuration-service:/opt/lockss/storage
      - ./logs/lockss-configuration-service:/opt/lockss/logs

  lockss-metadata-service:
    build:
      context: docker/lockss-image
      args:
        SVC_NAME: ${MDQ_ART}
        SVC_VERSION: ${MDQ_VERSION}
        SVC_PORT: ${MDQ_REST_PORT}
    image: lockss/lockss-metadata-service:${MDQ_VERSION}
    ports:
      - "${MDQ_REST_PORT}:${MDQ_REST_PORT}"
      - "${MDQ_UI_PORT}:${MDQ_UI_PORT}"
    command: "${MDQ_CMD}"
    links:
      - lockss-configuration-service
      - lockss-metadata-pgsql
    volumes:
      - ./config/plugins:/opt/lockss/BOOT-INF/lib
      - ./config/cluster:/opt/lockss/config/cluster
      - ./config/host:/opt/lockss/config/host
      - ./config/lockss-metadata-service:/opt/lockss/config/lockss-metadata-service
      - ./storage/lockss-metadata-service:/opt/lockss/storage
      - ./logs/lockss-metadata-service:/opt/lockss/logs

  lockss-metadata-extraction-service:
    build:
      context: docker/lockss-image
      args:
        SVC_NAME: ${MDX_ART}
        SVC_VERSION: ${MDX_VERSION}
        SVC_PORT: ${MDX_REST_PORT}
    image: lockss/lockss-metadata-extraction-service:${MDX_VERSION}
    ports:
      - ${MDX_REST_PORT}:${MDX_REST_PORT}
      - ${MDX_UI_PORT}:${MDX_UI_PORT}
    command: "${MDX_CMD}"
    links:
      - lockss-configuration-service
      - lockss-metadata-pgsql
    volumes:
      - ./config/plugins:/opt/lockss/BOOT-INF/lib
      - ./config/cluster:/opt/lockss/config/cluster
      - ./config/host:/opt/lockss/config/host
      - ./config/lockss-metadata-extraction-service:/opt/lockss/config/lockss-metadata-extraction-service
      - ./storage/lockss-metadata-extraction-service:/opt/lockss/storage
      - ./logs/lockss-metadata-extraction-service:/opt/lockss/logs

  lockss-metadata-pgsql:
    image: postgres:9.6
    ports:
      - "${PGSQL_PORT}:${PGSQL_PORT}"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  lockss-poller:
    build:
      context: docker/lockss-image
      args:
        SVC_NAME: ${POL_ART}
        SVC_VERSION: ${POL_VERSION}
        SVC_PORT: ${POL_REST_PORT}
    image: lockss/lockss-poller:${POL_VERSION}
    ports:
      - ${POL_REST_PORT}:${POL_REST_PORT}
      - ${POL_UI_PORT}:${POL_UI_PORT}
    command: "${POL_CMD}"
    links:
      - lockss-configuration-service
    volumes:
      - ./config/plugins:/opt/lockss/BOOT-INF/lib
      - ./config/cluster:/opt/lockss/config/cluster
      - ./config/host:/opt/lockss/config/host
      - ./config/lockss-poller:/opt/lockss/config/lockss-poller
      - ./storage/lockss-poller:/opt/lockss/storage
      - ./logs/lockss-poller:/opt/lockss/logs

  lockss-repository-service:
    image: lockss/lockss-repository-service:${REPO_VERSION}
    ports:
      - ${REPO_REST_PORT}:${REPO_REST_PORT}
    command: "${REPO_CMD}"
    environment:
      - "JVM_ARGS=${REPO_JARGS}"
      - REPO_MAX_WARC_SIZE
      - SOLR_HOST
      - SOLR_PORT
      - HDFS_HOST
      - HDFS_FSMD
    links:
      - lockss-solr
      - lockss-hdfs
    volumes:
      - ./config/lockss-repository-service:/opt/lockss/config/lockss-repository-service

  lockss-solr:
    build:
      context: docker/lockss-solr
    image: lockss/lockss-solr
    ports:
      - "${SOLR_PORT}:${SOLR_PORT}"
    command: "${SOLR_CMD}"

  lockss-hdfs:
    image:  lockss/lockss-dev-hdfs
    ports:
      - "${HDFS_FSMD}:${HDFS_FSMD}"
      - "${HDFS_DATA}:${HDFS_DATA}"
      - "${HDFS_MD}:${HDFS_MD}"
      - "${HDFS_STATUI}:${HDFS_STATUI}"
      - "${HDFS_DNUI}:${HDFS_DNUI}"
    environment:
      - HDFS_HOST
      - HDFS_FSMD
      - HDFS_DATA
      - HDFS_MD
      - HDFS_STATUI
      - HDFS_DNUI
    volumes:
      - ./config/lockss-hdfs/etc/hadoop:/hadoop/etc/hadoop.custom

  lockss-openwayback:
    image: lockss/lockss-openwayback
    ports:
    - "${WAYBACK_URL_PORT}:${WAYBACK_URL_PORT}"
    links:
    - lockss-hdfs
    environment:
    - HDFS_HOST
    - HDFS_FSMD
    - REPO_BASEDIR
    - WAYBACK_URL_PORT
    - WAYBACK_URL_HOST
    - WAYBACK_BASEDIR
    - WAYBACK_HDFSMNT
    - WAYBACK_WATCHDIR
    devices:
    - /dev/fuse
    cap_add:
    - SYS_ADMIN

  lockss-pywb:
    build:
      context: docker/lockss-pywb
    image: lockss/lockss-pywb
    ports:
      - "${PYWB_URL_PORT}:${PYWB_URL_PORT}"
    links:
      - lockss-hdfs
    environment:
      - HDFS_HOST
      - HDFS_FSMD
      - REPO_BASEDIR
      - PYWB_URL_PORT
      - PYWB_URL_HOST
      - PYWB_COLLECTION
      - PYWB_BASEDIR
      - PYWB_HDFSMNT
      - PYWB_WATCHDIR
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
    - ./config/lockss-pywb/config.yaml:/webarchive/config.yaml

  lockss-edina-indexer:
    image: lockss/lockss-edina-indexer
    links:
      - lockss-solr
      - lockss-hdfs
    environment:
      - HDFS_HOST
      - HDFS_FSMD
      - REPO_BASEDIR
      - LOCKSS_SOLR_HDFSMNT
      - LOCKSS_SOLR_WATCHDIR
      - LOCKSS_SOLR_WATCHDIR_INTERVAL
      - LOCKSS_SOLR_URL
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN