# Copyright (c) 2000-2019, Board of Trustees of Leland Stanford Jr. University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

version: '3'

#
# SERVICES
#
services:

  #
  # SERVICE lockss-configuration-service
  #
  lockss-configuration-service:
    image: 'lockss/lockss-configuration-service:${CFG_VERSION}'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    configs:
      - source: bootstrap
        target: /run/configs/lockss_bootstrap
      - source: cfg_service
        target: /run/configs/lockss_service
      - source: cfg_service_opt
        target: /run/configs/lockss_service_opt
    # add cluster to this when ready.
    environment:
      - LOCKSS_IS_CONFIG=true
      - LOCKSS_PROPS_URL: ${LOCKSS_PROPS_URL}
    ports:
      - "${CFG_REST_PORT}:${CFG_REST_PORT}"
      - "${CFG_UI_PORT}:${CFG_UI_PORT}"
      - "${JMS_PORT}:${JMS_DEFAULT_PORT}"
    links:
      - lockss-repository-service
    volumes:
      - lockss-cfg-data:/data
      - lockss-cfg-logs:/var/log/lockss

  #
  # SERVICE lockss-metadata-service
  #
  lockss-metadata-service:
    image: lockss/lockss-metadata-service:${MDQ_VERSION}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    configs:
      - source: bootstrap
        target: /run/configs/lockss_bootstrap
      - source: mdq_service
        target: /run/configs/lockss_service
      - source: mdq_service_opt
        target: /run/configs/lockss_service_opt
    ports:
      - "${MDQ_REST_PORT}:${MDQ_REST_PORT}"
      - "${MDQ_UI_PORT}:${MDQ_UI_PORT}"
    links:
      - lockss-configuration-service
      - lockss-metadata-pgsql
    volumes:
      - lockss-mdq-data:/data
      - lockss-mdq-logs:/var/log/lockss
    environment:
      - POSTGRES_HOST: ${POSTGRES_HOST}
      - POSTGRES_PORT: ${POSTGRES_PORT}
      - POSTGRES_USER: ${POSTGRES_USER}
      - LOCKSS_CONFIG_URL: ${LOCKSS_CONFIG_URL}
    secrets:
      - postgres_passwd

  #
  # SERVICE lockss-metadata-extraction-service
  #
  lockss-metadata-extraction-service:
    image: lockss/lockss-metadata-extraction-service:${MDX_VERSION}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    configs:
      - source: bootstrap
        target: /run/configs/lockss_bootstrap
      - source: mdx_service
        target: /run/configs/lockss_service
      - source: mdx_service_opt
        target: /run/configs/lockss_service_opt
    ports:
      - "${MDX_REST_PORT}:${MDX_REST_PORT}"
      - "${MDX_UI_PORT}:${MDX_UI_PORT}"
    links:
      - lockss-configuration-service
      - lockss-postgres
    volumes:
      - lockss-mdx-data:/data
      - lockss-mdx-logs:/var/log/lockss
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_DEFAULT_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - LOCKSS_CONFIG_URL=${LOCKSS_CONFIG_URL}
    secrets:
      - postgres_pass

  #
  # SERVICE lockss-poller
  #
  lockss-poller:
    image: lockss/lockss-poller:${POL_VERSION}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    configs:
      - source: bootstrap
        target: /run/configs/lockss_bootstrap
      - source: pol_service
        target: /run/configs/lockss_service
      - source: pol_service_opt
        target: /run/configs/lockss_service_opt
    ports:
      - ${POL_REST_PORT}:${POL_REST_PORT}
      - ${POL_UI_PORT}:${POL_UI_PORT}
    links:
      - lockss-configuration-service
    volumes:
      - lockss-pol-data:/data
      - lockss-pol-logs:/var/log/lockss
    environment:
      - LOCKSS_CONFIG_URL=${LOCKSS_CONFIG_URL}

  #
  # SERVICE lockss-repository-service
  #
  lockss-repository-service:
    image: lockss/lockss-repository-service:${REPO_VERSION}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    configs:
      - source: repo_service
        target: /run/configs/lockss_service
    ports:
      - ${REPO_REST_PORT}:${REPO_REST_PORT}
    environment:
      - "JVM_ARGS=${REPO_JARGS}"
      - REPO_MAX_WARC_SIZE
      - SOLR_HOST
      - SOLR_PORT
      - HDFS_HOST
      - HDFS_FSMD
    links:
      - lockss-solr
      - lockss-hdfs
    volumes:
      - lockss-repo-data: /data
      - lockss-repo-logs: /var/log/lockss

  #
  # SERVICE lockss-postgres
  #
  lockss-postgres:
    image: postgres:${POSTGRES_VERSION}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_DEFAULT_PORT}'
    volumes:
      lockss-postgres-data: /data
      lockss-postgres-logs: /var/logs/postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_passwd
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/data
        #for version 9
      - POSTGRES_INITDB_XLOGDIR=/var/log/postgres
        # for version 10+
      - POSTGRES_INITDB_WALDIR=/var/log/postgres

  #
  # SERVICE lockss-solr
  #
  lockss-solr:
    image: lockss/solr:${LOCKSS_SOLR_VERSION}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "${SOLR_PORT}:${SOLR_DEFAULT_PORT}"
    command: solr-precreate lockss
    volumes:
      lockss-solr-data: /opt/solr/server/solr/mycores
      lockss-solr-logs: /opt/solr/server/logs

  #
  # SERVICE lockss-hdfs
  #
  lockss-hdfs:
    image: lockss/lockss-hdfs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "${HDFS_FS}:${HDFS_DEFAULT_PORT}"
    volumes:
      - lockss-hdfs-data=/hadoop
      - lockss-hdfs-logs=/var/log/hadoop
  #
  # SERVICE lockss-pywb
  #
  lockss-pywb:
    image: lockss/lockss-pywb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "${PYWB_PORT}:${PYWB_DEFAULT_PORT}"
    links:
      - lockss-hdfs
    environment:
      - HDFS_HOST
      - HDFS_FSMD
      - REPO_BASEDIR
      - PYWB_URL_PORT
      - PYWB_URL_HOST
      - PYWB_COLLECTION
      - PYWB_BASEDIR
      - PYWB_HDFSMNT
      - PYWB_WATCHDIR
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
      - lockssvol:/config/lockss-pywb/config.yaml:/webarchive/config.yaml

  configs:
    cluster:
      external: true
    conf:
      external: true
    bootstrap:
      external: true
    cfg_service:
      external: true
    cfg_service_opt:
      external: true
    mdq_service:
      external: true
    mdq_service_opt:
      external: true
    mdx_service:
      external: true
    mdx_service_opt:
      external: true
    pol_service:
      external: true
    pol_service_opt:
      external: true
    repo_service:
      external: true

  volumes:
    lockss-cfg-data:
      external: true
    lockss-cfg-logs:
      external: true
    lockss-mdq-data:
      external: true
    lockss-mdq-logs:
      external: true
    lockss-mdx-data:
      external: true
    lockss-mdx-logs:
      external: true
    lockss-pol-data:
      external: true
    lockss-pol-logs:
      external: true
    lockss-repo-data:
      external: true
    lockss-repo-logs:
      external: true
    lockss-postgres-data:
      external: true
    lockss-postgres-logs:
      external: true
    lockss-solr-data:
      external: true
    lockss-solr-logs:
      external: true
    lockss-hdfs-data:
      external: true
    lockss-hdfs-logs:
      external: true
