data_sources: [ "defaults" , "file", "environment" ]
template_sources: [ "file" ]

defaults:

  lockss_bootstrap.erb:
    target: ../config/configs/lockss_bootstrap

  lockss_cluster.erb:
    target: ../config/configs/lockss_cluster

  cfg_service.erb:
    target: ../config/configs/cfg_service

  mdq_service.erb:
    target: ../config/configs/mdq_service

  mdx_service.erb:
    target: ../config/configs/mdx_service

  repo_properties.erb:
    target: ../config/configs/repo_properties

environments:
  docker: