data_sources: [ "defaults" , "file", "environment" ]
template_sources: [ "file" ]

defaults:

  lockss_bootstrap.erb:
    target: ../configs/lockss_bootstrap

  lockss_cluster.erb:
    target: ../configs/lockss_cluster

  cfg_service.erb:
    target: ../configs/cfg_service

  mdq_service.erb:
    target: ../configs/mdq_service

  mdx_service.erb:
    target: ../configs/mdx_service

  env.erb:
    target: ../../.env
