data_sources: [ "defaults" , "file", "environment" ]
template_sources: [ "file" ]

defaults:
  global:
    postgres_user: LOCKSS
    repo_port: 24610

  lockss_bootstrap.erb:
    target: ../configs/lockss_bootstrap.cfg

  lockss_cluster.erb:
    target: ../configs/lockss_cluster.cfg

  env.erb:
    target: ../../.env

environments:
  docker:
    cluster.erb:
      config:
        repo_host: lockss-repository-service
        jms_host: lockss-configuration-service